### PR TITLE
fixed internation page

### LINKED ISSUE #287: International page authoring and  styling
Author https://www.sling.com/international page and style to match with original sling page.

### PR DESCRIPTION
**Pull request by rusmeenkhan1**
Fix #287 

Test URLs:
- Before: https://main--sling--aemsites.aem.live/international
- After: https://287-international--sling--aemsites.aem.page/international

### CODE REVIEW

**Comment by helms-charity** [comment]
- Hero area in mobile is much different
- Check with customer why Desi Binge Plus package is only available on Mobile?
- Polish circle is missing on your page
image

File: aemedge/blocks/columns/columns.js [hunk 1]
```diff
@@ -42,4 +42,32 @@ export default async function decorate(block) {
...
+    'https://main--sling--aemsites.aem.live/international/eastasian/mandarin',
+    'https://main--sling--aemsites.aem.live/international/eastasian/taiwanese',
+  ];
+  const images = document.querySelectorAll('.columns div .columns-img-col img');
+  images.forEach((img, index) => {
+    const link = document.createElement('a');
+    link.href = links[index] || '#';
+    img.parentNode.insertBefore(link, img);
+    link.appendChild(img);
+  });
```
Comment (helms-charity) [inline aemedge/blocks/columns/columns.js:72]: Better would be to give the power to the authors for linking images anywhere they need to. If you put the link URL under each picture in your columns, then something like the below should do it (put this in "scripts"?) 
 
 ```
function decorateLinkedImages(main) {
  const pictures = main.querySelectorAll('picture');
  pictures.forEach((picture) => {
    const next = picture.nextElementSibling;
    if (next && next.tagName === 'A') {
      const a = next;
      a.replaceChildren(picture);
    } else if (next && next.tagName === 'BR' && next.nextElementSibling && next.nextElementSibling.tagName === 'A') {
      const a = next.nextElementSibling;
      a.replaceChildren(picture);
    }
  });
}
```

**Review by helms-charity — CHANGES_REQUESTED** [review]

File: aemedge/blocks/columns/columns.css [hunk 2]
```diff
@@ -66,24 +66,81 @@
   width: 80px;
 }
 
+.international .default-content-wrapper h2,h1{
+  text-align: center;
+}
```
Comment (helms-charity) [inline aemedge/blocks/columns/columns.css:71]: The H1 in the hero should not be centered.

**Review by helms-charity — APPROVED** [review]
I approved so you can merge once you remove the H1 from line 69.
